- .github/CODEOWNERS
- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- poetry.lock
- pyproject.toml
- wacruit/src/database/config.py
- wacruit/src/database/connection.py
- wacruit/src/database/migrations/env.py
- wacruit/src/secrets.py
1. CODEOWNERS 생성
2. AWS Role 생성
3. Github workflow 준비
4. CICD 용 AWS Access Key 시크릿 설정
> Use Aws Secret Manager & Prepare for Deployment

- wacruit/src/apps/judge/config.py
- wacruit/src/secrets.py
> Give default value to judge api url from secret manager

- wacruit/src/app.py
k8s에서 /api/* 경로만 accept 하므로 docs url 을 변경합니다.
> Change docs url

- .github/workflows/test.yaml
- wacruit/src/apps/common/schemas.py
- wacruit/src/apps/judge/connections.py
- wacruit/src/apps/judge/repositories.py
- wacruit/src/apps/judge/schemas.py
- wacruit/src/apps/problem/exceptions.py
- wacruit/src/apps/problem/models.py
- wacruit/src/apps/problem/repositories.py
- wacruit/src/apps/problem/schemas.py
- wacruit/src/apps/problem/services.py
- wacruit/src/apps/problem/views.py
- wacruit/src/database/__init__.py
- wacruit/src/database/config.py
- wacruit/src/database/migrations/env.py
- wacruit/src/tests/models/conftest.py
- wacruit/src/tests/problem/conftest.py
- wacruit/src/tests/problem/test_problem_repository.py
#4 는 코드 제출 로직만 구현했고, 이 PR에서는 아래와 같은 것들이 추가로 구현되었습니다.
* 채점 로직
* 시간 초과, 오답, 컴파일에러, 런타임에러 (judge0 api 적극 활용)
* 배치 api 사용하여 제출 로직 개선
* 테스트 제출 시 추가 테스트케이스 기능 구현
* 단일 문제 get api 추가 (해당 문제 예제 테케도 가져오도록 구현)
* 제출 코드 저장 로직 (본 제출 시만)
> 채점 및 제출 결과 저장 로직 구현

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- wacruit/src/admin/auth.py
- wacruit/src/admin/config.py
- wacruit/src/admin/views.py
- wacruit/src/app.py
- wacruit/src/apps/common/exceptions.py
- wacruit/src/apps/problem/models.py
- wacruit/src/apps/user/models.py
- wacruit/src/database/base.py
- wacruit/src/database/connection.py
- wacruit/src/secrets.py
- wacruit/src/utils/singleton.py
- sqladmin 사용했습니다.
- `env=local`에서는 아디비번 admin/admin 쓰시면 됩니다. dev 및 prod 환경에서의 아이디/비밀번호는 이후에 DM 드릴게요. secret manager 등록은 완료했습니다.
- jwt로 인증합니다.
- pylint 너무 느려서 전체 코어 다 쓰도록 옵션 줘봤는데 훨 낫네요
- Singleton 클래스 init에서 다른 Singleton init하려고 하면 데드락 걸려서 RLock으로 바꿨습니다.
- 일단 눈에 보이는 모델들만 추가했고 추후 필요에 따라 더 추가하면 될듯 합니다.
- `__str__`는 디테일 페이지에서 relationship 볼 때 필요합니다. 없으면 가독성이 떨어지네요.
> 어드민 페이지 추가

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
CD 할 때 마이그레이션도 하도록 추가했습니다.
PR 머지될 때마다 일일이 수동으로 마이그레이션하는 것보다 이게 나을 것 같아서 그랬는데,
막상 작성하고보니 production db는 수작업으로 마이그레이션하는 게 나을 것 같기도 하고,, 고민이 되네요
의견 남겨주세요 cc. @wafflestudio/waffledotcom-backend
> add migration command on contiguous deployment

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
> add ecr registry env to migration step

- Dockerfile
자꾸 하나씩 빠뜨리네요 ㅠ
cd는 디버깅하기가 어려워서리...
> add COPY of alembic.ini to image

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
> remove contiguous migration from deploy-*.yaml

- wacruit/src/apps/resume/exceptions.py
- wacruit/src/apps/resume/models.py
- wacruit/src/apps/resume/repositories.py
- wacruit/src/apps/resume/schemas.py
- wacruit/src/apps/resume/services.py
- wacruit/src/apps/resume/views.py
- wacruit/src/apps/user/exceptions.py
- wacruit/src/apps/user/services.py
- wacruit/src/tests/conftest.py
- wacruit/src/tests/resume/conftest.py
- wacruit/src/tests/resume/test_resume_service.py
- 원래 withdraw만 하려고 했는데, 수정이 필요한 곳들이 좀 보여서 resumes쪽 전반적으로 수정했습니다.
- API spec 변경
- 함수명 및 변수명 더 명확하게 변경
- withdraw api 추가
- create, update, withdraw API 에 대한 테스트 작성
- 논외지만 ResumeSubmission라는 이름이 좀 이상한듯.. ResumeQuestion ←→ ResumeAnswer이 더 적합한거같음
> Refactor resumes & add tests & withdraw

- wacruit/src/app.py
제 생각엔 dev 에만 적용되는게 좋을것 같은데, 일단 그런거 없이 빠르게 올렸습니다.
> feat: allow cors for localhost 5173

- wacruit/src/admin/formatters.py
- wacruit/src/admin/views.py
현재 대부분의 foreign key 들이 ondelete set null 로 되어 있어서, 해당 부분 admin 페이지에서 예외처리 추가하였습니다.
> admin 페이지에서 foreign key NULL일 때 예외처리

- wacruit/src/apps/user/repositories.py
- wacruit/src/apps/user/schemas.py
- wacruit/src/apps/user/services.py
- wacruit/src/apps/user/views.py
> check signup api

- wacruit/src/apps/portfolio/url/views.py
url param 받는 설정이 잘못되어있어 수정합니다.
> fix: Url API 수정

- wacruit/src/apps/judge/schemas.py
- wacruit/src/apps/problem/services.py
* kotlin compile 시 jvm target을 13으로 변경했습니다.
* kotlin 채점 시 batch submission을 사용하지 않도록 했습니다.
> Fix: kotlin compilation

- poetry.lock
- pyproject.toml
- wacruit/src/apps/hodu/repositories.py
- wacruit/src/apps/problem/repositories_v2.py
- wacruit/src/database/connection.py
* 코드 채점 시 에러가 발생할 때 리트라이 로직 추가
* MySQL Connection 에러 대응하여 pool 설정 추가
> Feat: 코드 채점 시 리트라이 로직 추가 (#69)

- wacruit/src/apps/faq/exceptions.py
- wacruit/src/apps/faq/services.py
- wacruit/src/apps/history/exceptions.py
- wacruit/src/apps/history/services.py
- wacruit/src/apps/seminar/exceptions.py
- wacruit/src/apps/seminar/services.py
> fix: 빈 리스트 반환

- wacruit/src/main.py
* 라우터가 중복으로 등록되어 생기는 경고 메세지가 나오지 않도록 수정했습니다
> fix: 라우터 중복 등록 수정

- wacruit/src/admin/views.py
* testcase의 stdin, expected_output이 Textarea로 보이도록 수정했습니다.
> fix: testcase 입력 수정

- wacruit/src/tests/timeline/conftest.py
- wacruit/src/tests/timeline/test_timeline_service.py
> chore: timeline 테스트 코드 작성

- wacruit/src/apps/problem/services_v2.py
* develop -> main 으로 갈 때 충돌이 일어나서 수정했습니다.
> fix: merge conflict 수정
